name: Kratt Neurokõne TTS
version: 0.1.1
slug: kratt_neurokone_tts
description: Estonian Wyoming TTS service using the Tartu Neurokõne API
url: https://github.com/Yikizi/kratt/tree/main/kratt-neurokone-tts
arch:
  - aarch64
  - amd64
startup: services
boot: auto
init: false
stage: experimental
discovery:
  - wyoming
ports:
  10301/tcp: null
ports_description:
  10301/tcp: Wyoming TTS protocol
options:
  voice: mari
  speed: 1.0
  debug_logging: false
schema:
  voice: str
  speed: float(0.5,2.0)
  debug_logging: bool
